### ISSUE TITLE
想问一下这类html游戏的汉化是怎么做的

### ISSUE THREAD

**Issue by Anahita-C** [NumberSir/vrelnir_localization#23]
我打算汉化一个html游戏，但是空有翻译力没有技术力，所以来咨询了

**Comment by NumberSir** [comment]
https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/issues/449#issuecomment-2509788837

**Comment by NumberSir** [comment]
不对，你都到这里了怎么还问这个
核心就只有四步，第一步是找到游戏内要汉化的文本，第二步是提取出来，第三步是汉化，第四步是替换回去。
如果你只能翻译的话，剩下的三步需要找有技术力的人来搞。
